name: Update README

on:
  schedule:
    - cron: "0 */12 * * *"

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: anmol098/waka-readme-stats@master
